### ISSUE TITLE
ml.chapter generates invalid href tags in json

### ISSUE THREAD

**Issue by m4p** [podlove/metalove#8]
If the MP3 contains invalid chapter links (e.g. " " or " ."), ml.chapter generates a json chapter fragment that causes the webplayer to discard all of the chapter information. I guess either check for link validity or escalate the ticket to the webplayer for more graceful error handling.

Example input file: http://media.subethanet.org/fanboys/FAN357.mp3

**Comment by m4p** [comment]
[ChaptersFragment.json.zip](https://github.com/podlove/metalove/files/3362185/ChaptersFragment.json.zip)

**Comment by monkeydom** [comment]
fixed in 60667078e4be8e7afed2d8dfe51e38d68f96bbc0
